language: python
sudo: false
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - buildout
script:
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls
