language: python
sudo: false
python:
  - 2.7
install:
  - pip install -r requirements-dev.txt
# force failure of code analysis
  - buildout code-analysis:return-status-codes=True
script:
  - bin/code-analysis
  - pytest z3c --cov z3c --cov-report term-missing
after_success:
  - coveralls
