name: Testing
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test:
    name: Testing on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.10", 3.9, 3.8, 3.7, pypy-3.9]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
      - name: pip version
        run: pip --version
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      # formatters
      - name: Run pyupgrade
        if: matrix.python-version == '3.11'
        run: pyupgrade --py37-plus setup.py `find z3c -name "*.py"`
      - name: Run isort
        if: matrix.python-version == '3.11'
        run: isort --check-only setup.py z3c/
      - name: Run black
        if: matrix.python-version == '3.11'
        run: black --check --skip-string-normalization setup.py z3c/
      # linters
      - name: Lint with codespell
        if: matrix.python-version == '3.11'
        run: codespell *.rst setup.py z3c/
      - name: Lint with flake8
        if: matrix.python-version == '3.11'
        run: flake8 setup.py z3c/ --count --show-source --statistics
      # tests and coverage
      - name: Test
        run: pytest
      - name: Coverage
        run: coveralls --service=github
